services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DB_FILE_NAME=./db/app.db
    env_file:
      - .env.local
    ports:
      - "3000:3000"
    working_dir: /app
    depends_on: []
    restart: unless-stopped
