name: deploy to AppRun

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create litestream config
        env:
          SAKURA_STORAGE_BUCKET_NAME: ${{ vars.SAKURA_STORAGE_BUCKET_NAME }}
          SAKURA_STORAGE_KEYID: ${{ secrets.SAKURA_STORAGE_KEYID }}
          SAKURA_STORAGE_SECRET: ${{ secrets.SAKURA_STORAGE_SECRET }}
          APP_NAME: stack-compass
          DB_FILE_NAME: /app/db/app.db
        run: ./scripts/common-litestream-config.sh > ./litestream.yml

      - name: Deploy to AppRun
        id: deploy
        uses: rito528/sacloud-apprun-action@v8
        with:
          use-repository-dockerfile: true
          app-dir: .
          sakura-api-key: ${{ secrets.SAKURA_API_TOKEN }}
          sakura-api-secret: ${{ secrets.SAKURA_API_SECRET }}
          container-registry: ${{ vars.CONTAINER_REGISTRY_URL }}
          container-registry-user: ${{ vars.CONTAINER_REGISTRY_USERNAME }}
          container-registry-password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
          object-storage-bucket: ${{ vars.SAKURA_STORAGE_BUCKET_NAME }}
          object-storage-access-key: ${{ secrets.SAKURA_STORAGE_KEYID }}
          object-storage-secret-key: ${{ secrets.SAKURA_STORAGE_SECRET }}
          port: '3000'
          auth-github-id: ${{ secrets.AUTH_GITHUB_ID }}
          auth-github-secret: ${{ secrets.AUTH_GITHUB_SECRET }}
          auth-secret: ${{ secrets.AUTH_SECRET }}
          db-file-name: "/app/db/app.db"
          database-url: "/app/db/app.db"
          auth-url: "https://app-e75a0946-2227-47e9-a56f-f92cbb6f79a3.ingress.apprun.sakura.ne.jp/"
