name: deploy to AppRun

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to AppRun
        id: deploy
        uses: rito528/sacloud-apprun-action@v6
        with:
          use-repository-dockerfile: true
          app-dir: .
          sakura-api-key: ${{ secrets.SAKURA_API_TOKEN }}
          sakura-api-secret: ${{ secrets.SAKURA_API_SECRET }}
          container-registry: ${{ vars.CONTAINER_REGISTRY_URL }}
          container-registry-user: ${{ vars.CONTAINER_REGISTRY_USERNAME }}
          container-registry-password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
          port: '3000'
          # SQLite + Litestream を使う場合は以下も指定
          object-storage-bucket: ${{ vars.SAKURA_STORAGE_BUCKET_NAME }}
          object-storage-access-key: ${{ secrets.SAKURA_STORAGE_KEYID }}
          object-storage-secret-key: ${{ secrets.SAKURA_STORAGE_SECRET }}
          sqlite-db-path: ./db/app.db
          litestream-replicate-interval: 10s
          auth-github-id: ${{ secrets.AUTH_GITHUB_ID }}
          auth-github-secret: ${{ secrets.AUTH_GITHUB_SECRET }}
          auth-secret: ${{ secrets.AUTH_SECRET }}
          db-file-name: ./db/app.db
          database-url: "file:./db/app.db"
          auth-url: "https://app-e75a0946-2227-47e9-a56f-f92cbb6f79a3.ingress.apprun.sakura.ne.jp/"
