name: Lint Dockerfile

on: 
  push:
      paths:
        - 'Dockerfile'
  pull_request:
      paths:
        - 'Dockerfile'
  workflow_dispatch:

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: "Dockerfile"

