name: Release Docker Image

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

on:
  # push:
    # tags:
    #   - 'v*'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v4

      - name: Login to Sakura Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.CONTAINER_REGISTRY_URL }}
          username: ${{ vars.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push to DockerHub and GHCR
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ vars.CONTAINER_REGISTRY_URL }}/${{ vars.CONTAINER_REGISTRY_USERNAME }}/${{ vars.CONTAINER_IMAGE_NAME }}:latest
            ${{ vars.CONTAINER_REGISTRY_URL }}/${{ vars.CONTAINER_REGISTRY_USERNAME }}/${{ vars.CONTAINER_IMAGE_NAME }}:${{ github.ref_name }}
